/**
 *this class holds the mark information for each student
*/
package ca.uwo.rbloomf;

import java.util.ArrayList;

/**
 *
 * @author Riley
 */
public class rbloomf_lab06_ReportCard {
    
    //number of marks each student has per course
    public int numMarksCourse = 4;
    
    //number is incremented when student is added to courses and decremented when they are dropped
    public int numCoursesInReport;
    
    //list of courses the student is registered in (null at first) no courses originally
    ArrayList<rbloomf_lab06_Course> coursesInReport = null;
    
    //2D array saves marks generated by the ranom generating function
    public int marks[][];
    
    //make a new list to hold the courses for each student
    //set the number of courses enrolled to 0 initially
    rbloomf_lab06_ReportCard() {
        coursesInReport = new ArrayList<>();
        numCoursesInReport = 0;
    }
    
    //this method assigns a random integer mark from 0-100 to every mark slot for all courses a student is registered in
    public void generateRandomMarks () {
        
        //create a new array (number of courses enrolled has probably changed since last generation)
        marks = new int[coursesInReport.size()][numMarksCourse];
        
        //go through every slot in the marks array and fill it with a random mark
        for (int i = 0; i<coursesInReport.size(); i++) {
            for (int j=0; j<numMarksCourse; j++) {
                marks[i][j] = 0 + (int)(Math.random()*101); //assign a random mark from 0 to 100
            }
        }
    }
    
}
